import type { Metadata } from "next";
import { Inter, Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import Header from '../components/Header';

const notoSansThai = Noto_Sans_Thai({
  subsets: ['latin', 'thai']
})

export const metadata: Metadata = {
  title: "MDCU Activity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansThai.className}>
        <Header/>
        {children}</body>
    </html>
  );
}
